/**
 * Enum for HTTP Methods
 */
 export enum ApiMethod {
    GET = 'GET',
    POST = 'POST',
    PUT = 'PUT',
    DELETE = 'DELETE',
    UPLOAD = 'UPLOAD',
    DOWNLOAD = 'DOWNLOAD'
}

/**
 *  API endpoints
 */
export enum ApiEndpoints {
    LOGIN = 'auth/login',
    SOCIAL_LOGIN = '/public/social-login',
    LOGGEDIN_USER_DETAILS = '/auth/user/loggedin-user-details',
    COVERAGE_TYPE_LIST = '/public/coverage-type/list',
    ORGANIZATION_TYPE_LIST = '/public/account-legal-type/list',
    USER_REGISTER = '/public/user-registration',
    BUSINESS_REGISTER = '/auth/business-registration/registration',
    GUEST_REGISTER = '/public/guest-registration',
    COVERAGE_CATEGORY_INFO = '/public/coverage-category-info/details',
    QUOTE_TYPE_LIST = '/public/guide-quote-type/list',
    QUOTE_TYPE_QUESTIONER = '/public/guide_quote_bonding/list',
    BONDING_CATEGORY_DETAILS = '/public/bond-category/details',
    INDUSTRY_EXPERIENCE_LIST = '/public/industry-experience/list',
    ACCOUNT_OWNER_LIST = '/public/account-owner-type/list',
    BONDING_PROFILE_QUESTIONS = '/public/bonding-profile-question/list',
    BONDING_PROFILE_SUBMIT = '/auth/bonding-profile/add',
    COMPLETED_COVERAGES = '/auth/coverage-selection/completed',
    ALL_COVERAGES = '/auth/coverage-selection/selected',
    ADD_COVERAGES = '/auth/coverage-selection/addAll',
    BOND_FORM_LIST = '/auth/bond-form/search',
    BOND_FORM_PDF = '/auth/bond-form/view/',
    GUEST_USER_VERIFY = '/public/user/guest-user-verify',
    GUEST_CREATE_PASSWORD = '/public/user/create-password',
    BOND_FORM_REQUEST = '/auth/bond-form/request',
    COVERAGE_FORM_DETAILS = '/auth/generic-form-page/details',
    NAICS_CODE_LIST = '/auth/naics-code/list',
    COMMERCIAL_INSUARNCE_REGISTER = '/auth/commercial-insurance/register',
    COVERAGE_FORM_STORE = '/auth/coverage-form-data/store',
    COVERAGE_FORM_DATA = '/auth/coverage-form-data/get',
    FETCH_BUSINESS_REGISTER_FORM = '/auth/business-registration/view',
    EDIT_BUSINESS_REGISTER_FORM = '/auth/business-registration/edit',
    FETCH_BONDING_PROFILE_FORM = '/auth/bonding-profile/view',
    EDIT_BONDING_PROFILE_FORM = '/auth/bonding-profile/edit',
    GET_SELECTED_BOND_FORM = '/auth/bond-form/fetch',
    UPDATE_BOND_FORMS = '/auth/bond-form/update',
    COVERAGE_SELECTION_REVIEW = '/auth/coverage-selection/review',
    ALL_SELECTED_COVERAGES = '/auth/coverage-selection/selectionList',
    FETCH_BUSINESS_PROFILE = '/auth/business-profile/view',
    SUBMIT_BUSINESS_PROFILE = '/auth/business-profile/save',
    BOND_SUB_CATEGORY = '/auth/bond-sub-category/list',
    TIMEZONE_LIST = '/auth/time-zone/list',
    BID_SECURED_BY_LIST = '/auth/bid-secured-by/list',
    CONTRACT_BOND_SUBMIT = '/auth/contract-bond/store',
    FETCH_CONTRACT_BOND = '/auth/contract-bond/fetch',
    FETCH_CONTRACT_DETAIL = '/auth/contract-bond/details/fetch',
    CONTRACT_LIST = '/auth/contract-projects/list',
    TYPE_OF_WORK_LIST = '/auth/type-of-work/list',
    SUBMIT_CONTRACT_DETAILS = '/auth/contract-bond/details/store',
    OBLIGEE_LIST = '/auth/obligee/list',
    STATE_PROVINCE = '/auth/state-province/list',
    ACCOUNT_OWNER = '/auth/account-owner/list',
    CONTRACT_QUESTIONNAIRE = '/auth/contract-bond/questionnaire',
    PARTIALLY_COMPLETED_QUOTES = '/auth/client-quotes/partially-completed',
    PENDING_APPROVAL_QUOTES = '/auth/client-quotes/pending-approval',
    APPROVED_QUOTES = '/auth/client-quotes/approved',
    EDIT_BUSINESS_PROFILE = '/auth/business-profile/edit',
    REVIEW_SUBMIT_API = '/auth/coverage-selection/submit-request',
    REMOVE_SELECTED_COVERAGE = '/auth/coverage-selection/remove',
    REMOVE_BOND_FORM = '/auth/bond-form/remove',
    REQUIRED_SUPPORTING_DOCS = '/auth/supporting-document/required-document',
    SUBMIT_UPLOADED_DOCS = '/auth/supporting-document/store',
    REMOVE_UPLOADED_DOC = '/auth/supporting-document/remove',
    FETCH_QUOTES_DETAILS = '/auth/purchase-quotes/quotes-details',
    UPDATE_QUOTE_DETAILS = '/auth/purchase-quotes/get-expiry-date',
    SUBMIT_QUOTES_DETAILS = '/auth/purchase-quotes/effective-date-edit',
    CREDIT_CARD_TYPE_LIST = '/auth/credit-card-type/list',
    PAYMENT_SHIPPING_METHOD = '/auth/shipping-method/list',
    PAYMENT_ADDRESS_LIST = '/auth/payment/address/list',
    PAYMENT_CREDIT_CARD_LIST = '/auth/credit-card/list',
    PAYMENT_SUMMARY_COST = '/auth/payment-flow/payment-summary',
    PAYMENT_PAY = '/auth/payment/pay',
    FETCH_WORKERS_COMPENSATION = '/auth/workers-compensation/fetch',
    SUBMIT_WORKERS_COMPENSATION = '/auth/workers-compensation/store',
    ADDRESS_LIST = '/auth/commercial-property/fetch',
    ALARM_TYPE_LIST = '/auth/alarm-type/list',
    CONSTRUCTION_TYPE_LIST = '/auth/construction-type/list',
    STEEL_GRADE_LIST = '/auth/steel-grade/list',
    MASONRY_GRADE_LIST = '/auth/masonry-grade/list',
    SUBMIT_COMMERCIAL_PROPERTY = '/auth/commercial-property/store',
    PAYMENT_ECHECK_TYPE_LIST = '/auth/echeck-type/list',
    PAYMENT_ECHECK_ACCOUNT_LIST = '/auth/echeck-account/list',
    POLICY_INFO_FETCH = '/auth/policy-information/fetch',
    POLICY_INFO_STORE = '/auth/policy-information/store',
    POLICY_ADDITIONAL_QUESTION = '/auth/policy-information/fetch',
    ADDITIONAL_POLICY_FIELDS = '/auth/additional-application-questions/fetch',
    AGREEMENT_WAIVE_ON_FILE_INDEMNITY_FETCH = '/auth/waive-on-file-indemnity/fetch',
    AGREEMENT_WAIVE_ON_FILE_INDEMNITY_STORE = '/auth/waive-on-file-indemnity/store',
    AGREEMENT_IDEMNITY_MODAL = '/auth/indemnity-confirmation-modal/fetch',
    AGREEMENT_WET_INK_IDEMNITY_DOWNLOAD = '/auth/wet-ink-indemnity/download',
    AGREEMENT_WET_INK_INDEMNITY_UPLOAD = '/auth/wet-ink-indemnity/upload',
    AGREEMENT_ElECTRONIC_IDEMNITY_OWNERS_LIST = '/auth/electronic-indemnity/owners-list',
    AGREEMENT_ElECTRONIC_IDEMNITY_SEND_FOR_SIGN = '/auth/electronic-indemnity/send-for-sign',
    CLINET_LOGIN = '/agent/client-masquerade',
    FORGOT_PASSWORD = '/public/user/forgot-password',
    CLIENT_PROFILE_CONTACT_LIST = '/auth/client-business-profile/contact-list',
    CLIENT_PROFILE_CONTACT_SINGLE = '/auth/client-business-profile/contact-details',
    POSITION_TITLE_LIST = '/auth/position-title/list',
}

export enum ErrorMessage {
    LOGIN_FAILURE = 'You have entered an invalid Email or Password.',
    MESSAGE_400 = 'Your request could not be processed',
    MESSAGE_404 = 'Not found!',
    MESSAGE_408 = 'Request timeout!',
    MESSAGE_500 = 'Something went wrong. Please contact support.',
    MESSAGE_502 = 'Connection error.',
    MESSAGE_503 = 'Service Unavailable.',
    MESSAGE_504 = 'Connection error.',
    USERREGISTER_FAIL = 'Could not register user.',
}

export enum AppKey {
    USER_SESSION = '_utoken'
}